categories = {
    'cecil b. demille award' : [['cecil','demille'],['award']], 
    'best motion picture - drama': [["best"],["motion picture","movie","film"],"drama",("tv","television","act")], 
    'best performance by an actress in a motion picture - drama': [["best"],["actress"],["motion picture","movie"],"drama",("tv","television","supporting")], 
    'best performance by an actor in a motion picture - drama': [["best"],["actor"],["motion picture","movie"],"drama",("tv","television","supporting")], 
    'best motion picture - comedy or musical': [["best"],["motion picture","movie","film"],["musical","comedy"],("tv","television","act")], 
    'best performance by an actress in a motion picture - comedy or musical':[["best"],["actress"],["motion picture","movie"],["comedy","musical"],("tv","television","supporting")], 
    'best performance by an actor in a motion picture - comedy or musical': [["best"],["actor"],["motion picture","movie"],["comedy","musical"],("tv","television","supporting")], 
    'best animated feature film': ["best",["animation","animated"],["film","feature","motion picture"]], 
    'best foreign language film': ["best",["foreign"],["motion picture","film"]], 
    'best performance by an actress in a supporting role in a motion picture':[["best"],["actress"],["supporting"],["motion picture","movie"],"drama",("tv","television")], 
    'best performance by an actor in a supporting role in a motion picture': [["best"],["actor"],"supporting",["motion picture","movie"],"drama",("tv","television")], 
    'best director - motion picture': ["best","director"], 
    'best screenplay - motion picture': ["best", "screenplay"], 
    'best original score - motion picture': ["best",["original score","score"]], 
    'best original song - motion picture': ["best",["original song"]], 
    'best television series - drama': ["best",["tv","television","series"],"drama",("actor","actr")],
    'best performance by an actress in a television series - drama': ["best","actress",["tv","television","series"],"drama",("supporting","film")], 
    'best performance by an actor in a television series - drama': ["best","actor",["tv","television","series"],"drama",("supporting","film")], 
    'best television series - comedy or musical': ["best",["tv","television","series"],["musical","comedy"],('actor','actr')], 
    'best performance by an actress in a television series - comedy or musical': ["best","actress","supporting",["television","tv"],["musical","comedy"],("supporting","film")], 
    'best performance by an actor in a television series - comedy or musical':["best","actor","supporting",["television","tv"],["musical","comedy"],("supporting","film")], 
    'best mini-series or motion picture made for television': ["best",["television","tv"],["mini-series","limited series","made for","tv movie","television movie"],('actor','actr')], 
    'best performance by an actress in a mini-series or motion picture made for television': ["best","actress",["television","tv"],["mini-series","limited series","made for","tv movie","television movie"],("supporting","supports")], 
    'best performance by an actor in a mini-series or motion picture made for television': ["best","actor",["television","tv"],["mini-series","limited series","made for","tv movie","television movie"],("supporting","supports")], 
    'best performance by an actress in a supporting role in a series, mini-series or motion picture made for television': ["best","actress","supporting",["television","tv"],["mini-series","limited series","made for","tv movie","television movie"]],
    'best performance by an actor in a supporting role in a series, mini-series or motion picture made for television': ["best","actor","supporting",["television","tv"],["mini-series","limited series","made for","tv movie","television movie"]],
    'best motion picture - musical or comedy': 'best motion picture - comedy or musical',
    'best performance by an actress in a motion picture - musical or comedy': 'best performance by an actress in a motion picture - comedy or musical', 
    'best performance by an actor in a motion picture - musical or comedy': 'best performance by an actor in a motion picture - comedy or musical', 
    'best performance by an actress in a supporting role in any motion picture': 'best performance by an actress in a supporting role in a motion picture', 
    'best performance by an actor in a supporting role in any motion picture': 'best performance by an actor in a supporting role in a motion picture', 
    'best motion picture - animated': 'best animated feature film',  
    'best motion picture - foreign language':'best foreign language film',
    'best television series - musical or comedy':'best television series - comedy or musical', 
    'best television limited series or motion picture made for television':'best mini-series or motion picture made for television', 
    'best performance by an actress in a limited series or a motion picture made for television':'best performance by an actress in a mini-series or motion picture made for television', 
    'best performance by an actor in a limited series or a motion picture made for television':'best performance by an actor in a mini-series or motion picture made for television', 
    'best performance by an actress in a television series - musical or comedy':'best performance by an actress in a television series - comedy or musical', 
    'best performance by an actor in a television series - musical or comedy':'best performance by an actor in a television series - comedy or musical', 
    'best performance by an actress in a supporting role in a series, limited series or motion picture made for television':'best performance by an actress in a supporting role in a series, mini-series or motion picture made for television',
    'best performance by an actor in a supporting role in a series, limited series or motion picture made for television':'best performance by an actor in a supporting role in a series, mini-series or motion picture made for television'
}
stopwords = ["from","flick","npi","geht","into","person","night","show","yada","news","yet","played","laugh","acr","nom","dmp","a film"," na","not","far","cover","para","muy","music","n'","edu","friend","while"," x ","very","group","star","male","now","i ","dance","youtube","haha","combo"," es ","aka","hollywood","arm","beard","parent"," en","joke","carpet","dress","olden","look","moment","award","the","--","hosts","ever","speech","win", "is","should","and","as"," to ","movie","nominee","leading","ss -","or -","reviews"," of ","advice","humor","  ","party","celeb","t pi","r,","t fi","t dr"," so ","quote","go","nose","hair","photo","thing","tonight","eyes","still","wow","comm","\xa0","like","love","hate"," at" "for s","flick"]